### ISSUE TITLE
test.yml does not use new --sandbox syntax

### ISSUE THREAD

**Issue by Sbozzolo** [alphapapa/makem.sh#13]
Thanks for this beautifully useful and simple tool.

I followed the steps in the readme and added the `test.yml` to my `ivy-emoji` package (removing the sections were tests are run). The action fails at the "Initialize sandbox" stage with errors like
```
ERROR (2020-02-22 03:21:56): Invalid rule: /tmp/tmp.uOo3g4Aav2
```
Recent commits changed how `--sandbox` works, but the `test.yml` file is lagging behind. Changing the syntax in the `test.yml` to the new one fixes this problem.

**Comment by alphapapa** [comment]
Thank you very much.  I should have caught that myself.  I guess I need to write tests for the tests for the tests for the...  :)

**Comment by alphapapa** [comment]
BTW, I saw in your ivy-emojis repo that having makem.sh in it caused it to be classified as a Shell project instead of Emacs Lisp.  I just added some documentation about how to fix that: https://github.com/alphapapa/makem.sh#github-linguist-statistics

**Comment by Sbozzolo** [comment]
Thanks, I'll fix that.


alphapapa writes:

> BTW, I saw in your ivy-emojis repo that having makem.sh in it caused it to be classified as a Shell project instead of Emacs Lisp.  I just added some documentation about how to fix that: https://github.com/alphapapa/makem.sh#github-linguist-statistics
