### ISSUE TITLE
Accept different casing for package-requires

### ISSUE THREAD

**Issue by DamienCassou** [alphapapa/makem.sh#17]
I noticed that makem.sh only accepts "Package-Requires" and not "Package-requires". According to the Elisp info manual, you are absolutely right. However, package-lint ignores case: https://github.com/purcell/package-lint/blob/master/package-lint.el#L902. Melpa also ignores case.

I don't know what is best and you might want to just close my issue. Otherwise, you can change your code to ignore case as well :-).

**Comment by alphapapa** [comment]
Thanks.  I'm not sure what is best either, but I guess it's better to reflect what is actually accepted by other tools.
