### ISSUE TITLE
(Feature Request): Documentation generation

### ISSUE THREAD

**Issue by jethrokuan** [alphapapa/makem.sh#27]
Would you consider adding support for documentation generation via Org?

I've been trying to replicate the Make flows for Magit and use-package for documentation generation, and having it live together with makem's build and test-related generation. Documentation generation only requires using org, and installing https://github.com/tarsius/ox-texinfo-plus, which can be done in the sandbox.

I figured that having Makem generate a sandbox that is also capable of generating docs will simplify a lot of the setup that magit etc. uses here:

https://github.com/magit/magit/blob/master/default.mk#L194

**Comment by alphapapa** [comment]
I'm willing to consider it, but it would be a departure from the purpose so far, because there has been no generation or building done, only running tests and linters.  But I'm not opposed to this sort of thing in general.

However, I'm not sure if it's necessary.  Following Magit's example, I generate documentation for `org-super-agenda` and `org-ql` from Org files, but it's triggered with `after-save-hook` in Emacs when I save the `README.org` file.  What would the benefit be of doing this from `makem.sh` separately?

**Comment by jethrokuan** [comment]
> What would the benefit be of doing this from makem.sh separately?

It ensures that the documentation is generated from a consistent environment, similar to how the tests are now run in a consistent, sandboxed environment. This is, of course, much less important than having tests run in a consistent environment, but would be helpful when there is more than one person editing the README.

**Comment by alphapapa** [comment]
That's understandable, in general.  Can you give me an example of a specific problem that it would solve?  IME, a problem like this is the differing Texinfo output given by different Org versions: if I save some of my readmes with Org 9.1, the output is different than that of Org 9.3.  But it's not straightforward for `makem.sh` to control which Org version is installed into a sandbox--unless that were easily solved, users would have to do that manually.  And in that case, they could use, e.g. `emacs-sandbox.sh` to do that already.  So I'm not convinced that this feature would be useful or feasible at this time.

I'm also wary of adding support for too specific a workflow, e.g. one depending on specific third-party packages and versions.  The more specific it is, the more brittle, and the more likely that I'll have to fix things that break when third-party code changes in the future.

What do you think?  Thanks.

**Comment by jethrokuan** [comment]
I eventually went with the same approach as you, regenerating the texi and info on save, and the online docs using a github action calling `makeinfo` :smile:
