### ISSUE TITLE
Emacs 28: Sandboxing does not work

### ISSUE THREAD

**Issue by noctuid** [alphapapa/makem.sh#34]
I'm on the latest commit of makem.sh and using lucid Emacs 28 (master as of a few weeks ago) with native compilation. `./makem.sh -vvv --sandbox=./sandbox --install-deps` says it's using the sandbox, but it's actually using `~/.emacs.d/elpa`. The only thing it puts in the sandbox directory is an init.el. Let me know if there's any other useful information I can provide.

**Comment by alphapapa** [comment]
Thanks, I think I need to apply the same fix I did here: https://github.com/alphapapa/emacs-sandbox.sh/commit/4195987ee28e9855739cea7137c8501629b40922

**Comment by alphapapa** [comment]
After further testing, I'm not sure that fix was sufficient there, either.  `package-user-dir` ends up being set correctly, but apparently that happens after early-init calls `package-initialize` and sets `load-path`, so then I can't load any installed packages.

**Comment by alphapapa** [comment]
Looks like just calling `package-initialize` manually after setting `package-user-dir` fixes that.  And `emacs-sandbox.sh` was already calling `package-initialize`, but after it loaded the init file, which is backwards.

**Comment by alphapapa** [comment]
Ok, I think this fixes it properly in `emacs-sandbox.sh`: https://github.com/alphapapa/emacs-sandbox.sh/commit/ca92038285bd51d9ac6565f40fa029d10f97d062  So those changes need to be made here, too.

**Comment by noctuid** [comment]
It looks like this is working correctly in ed096a76cd016782d5390dd48647b6334ff907d1.  Is there anything else that needs to be changed?

**Comment by alphapapa** [comment]
You tell me.  :)  It seems to work correctly for me as well now.  Thanks.
