### ISSUE TITLE
Integrate indent-lint

### ISSUE THREAD

**Issue by DamienCassou** [alphapapa/makem.sh#4]
I've planned to add [indent-lint](https://github.com/conao3/indent-lint.el) to makel. If you beat me to it before me, it will help me migrate my project to makem.sh instead of spending time improving makel :-).

**Comment by alphapapa** [comment]
Hi Damien,

Thanks for the suggestion!  I think that should do it.  Please let me know what you think.  :)

**Comment by DamienCassou** [comment]
Thank you very much.
