### ISSUE TITLE
Install the correct dependency version into the sandbox

### ISSUE THREAD

**Issue by josephmturner** [alphapapa/makem.sh#41]
Example problem: When a built-in dependency has newer version available on ELPA, and the newer version is specified in the `Package-Requires` of our package, the newer version is not installed, and makem tests our package using the older, built-in version.

`makem` could call `package-install` to install the library as a package, which would use the built-in machinery to install dependencies at their correct versions.

**Comment by alphapapa** [comment]
Thanks.

**Comment by josephmturner** [comment]
IIUC, this bug is causing the `hyperdrive.el` [build manifests to fail](https://builds.sr.ht/~ushin/job/1069448#task-all) since the tests are running with the built-in version instead of the latest version which includes [this fix](https://github.com/magit/transient/issues/256).

**Comment by josephmturner** [comment]
Thank you!!
