### ISSUE TITLE
Loading `package` loads some other libraries, which may mask missing requirements

### ISSUE THREAD

**Issue by alphapapa** [alphapapa/makem.sh#47]
See https://github.com/melpa/melpa/pull/9062#issuecomment-2172520584

**Comment by alphapapa** [comment]
@josephmturner This seems to work.  With the changes on branch https://github.com/alphapapa/makem.sh/tree/wip/avoid-loading-package, compiling `org-transclusion-http` at ebbeba0 shows:
```
src/org-transclusion-http/makem.sh -v --emacs\=emacs-29.3 --sandbox\=.sandbox lint-compile
LOG (2024-06-17 03:30:43): Linting compilation...
LOG (2024-06-17 03:30:43): Compiling...

In toplevel form:
org-transclusion-http.el:69:4: Error: url is not a struct name
ERROR (2024-06-17 03:30:43): Linting compilation failed.
LOG (2024-06-17 03:30:43): Finished with 1 errors.
```

**Comment by josephmturner** [comment]
Thanks for the fix!  This seems to work except for a typo.  There' s a missing backslash in the `sandbox` function, fixed on this branch: 

https://github.com/alphapapa/makem.sh/commit/2adfb42

**Comment by alphapapa** [comment]
Of course, that's what I get for copying and pasting.  Thanks.

**Comment by alphapapa** [comment]
By the way, I think this change is probably fine to make, but it would be good to give it some basic testing first, e.g. test it with a few packages, intentionally cause some byte-compilation errors and ensure that they're caught, etc.  If you have the time and interest to test it on a few like that, please do.

**Comment by josephmturner** [comment]
I tested with `org-transclusion-http`, where this patch fixed [this issue](https://github.com/melpa/melpa/pull/9062#issuecomment-2171811321).

I also tested with `hyperdrive.el` by commenting out the `(require 'plz)` sexp in `hyperdrive-lib.el`, and `makem` correctly reported `hyperdrive-lib.el:228:4: Error: plz-response is not a struct name`.

In `chordpro-mode.el`, I commented out `(require 'thingatpt)`, and `makem` correctly reported `chordpro-mode.el: Error: the function thing-at-point-looking-at is not known to be defined.`

**Comment by alphapapa** [comment]
Thank you!
