### ISSUE TITLE
Indent-lint limitation

### ISSUE THREAD

**Issue by conao3** [alphapapa/makem.sh#5]
Thanks to find my package, [indent-lint](https://github.com/conao3/indent-lint.el/issues/10).
This package has below limitation for now.
- [x] multi file lint reported in https://github.com/conao3/indent-lint.el/issues/10
  - resolved by https://github.com/conao3/indent-lint.el/pull/14
- [x] needless footer output
  - resolved by https://github.com/conao3/indent-lint.el/pull/11
- [x] declare `indent` specification in Elisp files
  - resolved by https://github.com/conao3/indent-lint.el/pull/13

**Comment by alphapapa** [comment]
Thanks.

**Comment by conao3** [comment]
I resolved all the listed limitations. I'm not familiar with `makem`, so please test indent-lint through `makem`.

**Comment by alphapapa** [comment]
Thanks, will test again when MELPA rebuilds.

**Comment by DamienCassou** [comment]
Great example of a successful collaboration. Thank you guys.

**Comment by alphapapa** [comment]
@conao3 FYI, there's just one more issue: when there is an indentation mismatch, the function `indent-lint-batch` does not use `(kill-emacs 1)`, which prevents the calling script from detecting whether any indentation mismatches were detected.

I could work around this in `makem.sh` by providing a wrapper, but I'm guessing you'd prefer to fix it in `indent-lint` to match  the behavior of, e.g. `package-lint-batch-and-exit` and `ert-run-tests-batch-and-exit`.

Thanks.

**Comment by alphapapa** [comment]
@conao3 BTW, @noctuid just pointed me to https://github.com/gonewest818/elisp-lint, which includes this simple function to test indentation.  Maybe you'll find it useful: https://github.com/gonewest818/elisp-lint/blob/master/elisp-lint.el#L169

**Comment by conao3** [comment]
Exitcode issue solved at https://github.com/conao3/indent-lint.el/pull/22.
And thanks for letting me know `elisp-lint` project.

**Comment by alphapapa** [comment]
Thanks!
