### ISSUE TITLE
Add support for relint

### ISSUE THREAD

**Issue by DamienCassou** [alphapapa/makem.sh#8]
https://github.com/mattiase/relint

**Comment by alphapapa** [comment]
I'd be glad to add support for this, but it doesn't seem to have a `batch-and-exit`-style command to exit Emacs non-zero if problems are found.  I could add a wrapper for it like I did for `checkdoc`, but I'd prefer if `relint` gained that ability directly.  Would you mind looking into that?  Once it has that, it will be trivial to support it.

**Comment by DamienCassou** [comment]
https://github.com/mattiase/relint/issues/6

**Comment by DamienCassou** [comment]
@mattiase just fixed relint!

**Comment by alphapapa** [comment]
Thanks.  It works, but there is still some output when there are no errors or warnings.  Do you think the author would be willing to change that as well?  I'd like it to be consistent with other rules in that there should be no output when there are no errors or warnings.

https://github.com/alphapapa/makem.sh/tree/wip/relint

```
$ ./makem.sh -vv --sandbox-dir sandbox lint-checkdoc lint-regexps
LOG (2020-01-23 17:20:51): Linting checkdoc...
LOG (2020-01-23 17:20:52): Linting checkdoc finished without errors.
LOG (2020-01-23 17:20:52): Linting regexps...
relint: 0 errors.
LOG (2020-01-23 17:20:53): Linting regexps finished without errors.
LOG (2020-01-23 17:20:53): Finished without errors.
```

**Comment by alphapapa** [comment]
@DamienCassou Thanks!
